refactor: initialize `this.path` with `path`
pillarjs/router pull request #123
Opened 2024-09-25 12:26 UTC by IamLizu

- Fixes #122

2024-09-27 17:00 UTC, carpasse commented on lib/layer.js
> +  this.path = path
I think this property is expected to contain the matched `path` and not the possible array of paths of the

2025-03-05 17:01 UTC, wesleytodd requested changes

2025-03-05 17:01 UTC, wesleytodd commented on lib/layer.js
> +  this.path = path
Agreed, IIRC the idea here is that it is `undefined` until matched, then is also unset. You can see this in `.match`. I am pretty sure that means this would break the intended behavior.

2025-06-27 20:10 UTC, IamLizu commented
Thanks for clarifying the intent here. I’ll go ahead and close this for now.

2025-06-27 20:10 UTC, closed without merging