ci: updated github actions ci workflow
pillarjs/router pull request #143
Opened 2024-11-05 10:40 UTC by Phillip9587

closes #142 

The same has been done for `body-parser`: https://github.com/expressjs/body-parser/pull/546

2024-11-05 21:05 UTC, bjohansebas commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v4
```suggestion
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
```

It would be better to use the hash of the last commit of the version we want to use in each GitHub action, it's just to avoid opening another PR later.

Example: https://github.com/expressjs/compression/pull/205

2024-11-05 21:34 UTC, Phillip9587 commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v4
I don't recommend pinning GitHub actions with commit hashes, as it introduces a maintenance burden. Without an automatic dependency update system in place, manually updating these pinned hashes becomes cumbersome. In my opinion, using version tags like v4 ensures stability while allowing for easier maintenance and updates.

2024-11-05 21:39 UTC, Phillip9587 commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v4
As soon as a dependency update tool is implemented, I fully support pinning to commit hashes to ensure more controlled and reliable updates.

2024-11-05 22:34 UTC, bjohansebas commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v4
I would like to know your opinions @UlisesGascon @wesleytodd

2024-11-06 08:12 UTC, jonkoops commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v4
I would not bother pinning any actions from GitHub itself. The security risk there is basically non-existent. If those were ever compromised then that would be a world news level exploit. I am pretty sure the only reason this is recommend is that 3rd party actions are much more susceptible, and GitHub wants to cover their bases, hence the recommendation in the docs.

2024-11-11 14:02 UTC, wesleytodd requested changes
I am all 👍 on this, but put request changes so we can decide if we want to address the 1.x thing in this PR.

2024-11-11 14:02 UTC, wesleytodd commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v4
We need to do an RFC to align on this I think. We have typically considered the core platform ones "safe" in this reagard and the third party ones "unsafe". That said, I think we should have a more serious conversation on the pros/cons for the future. For example, I am strongly opposed to locking unless we have an auto update mechanism in place, ideally with some simple auto-merge logic (passed builds and one approval?).

For today, I think it is good to keep the ranges because that is also what we are doing in most repos.

2024-11-11 14:39 UTC, Phillip9587 commented on .github/workflows/ci.yml
> -      - '2.0'
@wesleytodd I think we should leave the v1 pipeline as it is in a separate 1.x branch. The 1.x branch needs to be tested on node.js version beginning with 0.8 while the master / 2.x branch does not support versions below v18. If we leave the 2 pipelines separate we just need to backport new node.js versions for 1.x.

2024-11-11 14:41 UTC, wesleytodd commented on .github/workflows/ci.yml
> -      - '2.0'
Ah good point. I think that is actually what we did other places. I was not thinking about that when I made this comment.

2024-11-11 14:41 UTC, wesleytodd approved these changes

2024-11-11 15:10 UTC, bjohansebas approved these changes

2024-11-11 16:40 UTC, UlisesGascon approved these changes

2024-11-11 16:43 UTC, UlisesGascon commented
Great point @wesleytodd!

I think that @inigomarquinez is working on several RFC(s) related to the OpenSSF Scorecard adoption that will cover how the locking + upgrade mechanism should work.

2024-11-12 17:41 UTC, wesleytodd commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v4
Lets call this resolved and move the conversation into an RFC so we can merge this improvement.

2024-11-12 17:41 UTC, merged